### ISSUE TITLE
Manage AngularJS file downloads

### ISSUE THREAD

**Issue by kensiprell** [Schlogen/angular-profile#2]
James,

Will this repo become the Grails 3.1 angular profile? I've got an old Grails project based on angular that I want to upgrade, but I've been waiting for official support.

Have you considered including a way to manage downloading the angularjs files?

[Craig Burke's Gradle plugin](https://github.com/craigburke/bower-installer-gradle) would be one way. I've started a [Gradle angularjs plugin](https://github.com/kensiprell/angularjs), but I've been waiting to see what happens with the official Grails support. I'd prefer my method over Craig's as it doesn't require anything other than what's delivered with Grails.

The heavy lifting is done [here](https://github.com/kensiprell/angularjs/blob/master/src/main/groovy/com/siprell/plugin/gradle/angularjs/AngularjsGradlePlugin.groovy). Right now, the plugin goes to work on [```processResources```](https://github.com/kensiprell/angularjs/blob/master/src/main/groovy/com/siprell/plugin/gradle/angularjs/AngularjsGradlePlugin.groovy#L35), but it'd be easy to change this to use a profile command instead.

My angular plugin is based on my [bootstrap-framework plugin](https://github.com/kensiprell/bootstrap-framework), which is a bit more mature. If you're interested in incorporating the ```AngularjsGradlePlugin``` class in your profile, I can double-check my work and make sure I haven't done anything stupid. The bootstrap-framework plugin is downloaded about six or seven times a day, so I've gotten feedback on it. I haven't looked at the angular plugin code in several months.

Ken

**Comment by Schlogen** [comment]
Ken,

Thank you for your inquiry. Yes this is the current work in progress Grails 3.1 Angular profile.

I attempted to use Craig Burke's gradle bower plugin, however due to an issue that only occurs in Windows, I was unable to test it. I think your plugin is great!

Here are the advantages I see of using the bower plugin over yours

1) It can install Angular as well as any other client side dependency, albeit with more configuration for the Angular side.
2) It comes with the node plugin which others might find useful for testing or other tasks

I do have a question for you, however. Can you explain the following: "I'd prefer my method over Craig's as it doesn't require anything other than what's delivered with Grails". What does Craig's require other than what's delivered with Grails?

**Comment by kensiprell** [comment]
James,

I've run into problems in the past with Grails plugins not being maintained, and so I've tried to reduce my reliance on them, preferring to roll my own. Additionally, I wanted to avoid having to rely on node.js and bower. I meant that once you've installed Grails 3.x, you need nothing else (no other dependencies) for the plugin to work. 

I agree, however, that Craig's work offers more options. However, I certainly prefer [my configuration options](https://github.com/kensiprell/angularjs-sample/blob/master/build.gradle#L4-L17). And yes, working with Windows file systems can be a problem for someone thinking only *nix. I test my plugins on a Windows VM and my Mac.

I'm just a hobby developer, so when I was writing my bootstrap and angular plugins for Gradle/Grails 3, I was looking for an easy way to avoid those repetitive download and move tasks. I was focused on the task at hand and not looking at the big picture. I suppose it'd be reinventing the bower wheel, otherwise I'd consider merging what I've done into one plugin to handle other client side dependencies.

Thanks for responding so quickly, and I'm really excited about Grails 3.1 and your angular profile. In my opinion the two were made for each other, and I was surprised when I first started learning about angular that hardly anyone else in the Grails world world was using it or so it seemed.

Ken
